import turtle as t
def draw_circle(x,y,r,clr):
    t.goto(x,y)
    t.up()
    t.forward(100)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(5)
    t.fillcolor(clr)
    t.begin_fill()
    t.circle(r)
    t.left(90)
    t.up()
    t.goto(x,y)
    t.setheading(0)
    t.end_fill()

     
def nose():
    t.up()
    t.forward(10)
    t.left(90)
    t.pencolor("black")
    t.pensize(5)
    t.fillcolor("pink")
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.goto(0,0)

def eye1(a,b,c):
    t.up()
    t.goto(40,40)
    t.forward(a)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("light green")
    t.begin_fill()
    t.circle(a)
    t.end_fill()
    t.up()
    t.goto(40,40)
    t.right(90)
    t.forward(b)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("red")
    t.begin_fill()
    t.circle(b)
    t.end_fill()
    t.up()
    t.goto(40,40)
    t.right(90)
    t.forward(c)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("blue")
    t.begin_fill()
    t.circle(c)
    t.end_fill()

def eye2(a,b,c):
    t.up()
    t.goto(-40,40)
    t.forward(a)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("light green")
    t.begin_fill()
    t.circle(a)
    t.end_fill()
    t.up()
    t.goto(-40,40)
    t.right(90)
    t.forward(b)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("red")
    t.begin_fill()
    t.circle(b)
    t.end_fill()
    t.up()
    t.goto(-40,40)
    t.right(90)
    t.forward(c)
    t.left(90)
    t.down()
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("blue")
    t.begin_fill()
    t.circle(c)
    t.end_fill()

def mouth():
    t.pencolor("black")
    t.pensize(2)
    t.fillcolor("white")
    t.begin_fill()
    t.right(90)
    t.circle(50,180)
    t.left(90)
    t.forward(100)
    t.end_fill()




    


def main():
    t.speed(0)
    draw_circle(0,0,100,"yellow")
    nose()
    eye1(20,10,5)
    eye2(20,10,5)
    t.up()
    t.goto(0,0)
    t.setheading(0)
    t.goto(-50,-30)
    mouth()
    t.done()
main()





